### ISSUE TITLE
Make this compliant with Laravel 5.1

### ISSUE THREAD

**Issue by kobelobster** [echo-it/laravel-jsonapi#17]
When trying to install v2.3, I'm getting the error

> Your requirements could not be resolved to an installable set of packages.

```
Problem 1
    - Conclusion: remove laravel/framework v5.1.1
    - Installation request for echo-it/laravel-jsonapi v2.3 -> satisfiable by echo-it/laravel-jsonapi[v2.3].
    - Conclusion: don't install laravel/framework v5.1.1
    - Conclusion: don't install laravel/framework v5.1.0
    - echo-it/laravel-jsonapi v2.3 requires illuminate/pagination 5.0.* -> satisfiable by illuminate/pagination[5.0.x-dev, v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4].
    - don't install illuminate/pagination 5.0.x-dev|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/pagination v5.0.0|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/pagination v5.0.22|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/pagination v5.0.25|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/pagination v5.0.26|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/pagination v5.0.28|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/pagination v5.0.33|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/pagination v5.0.4|don't install laravel/framework 5.1.x-dev
    - Installation request for laravel/framework 5.1.* -> satisfiable by laravel/framework[5.1.x-dev, v5.1.0, v5.1.1].
```

Seems like this package is not yet for Laravel 5.1, correct?

**Comment by egeriis** [comment]
It hasn't been tested with L5.1 yet. You're correct.

Feel free to force install it and test it out and do a pull request :+1:

**Comment by kobelobster** [comment]
Hi. This would be my first time working with this library. I don't know if I'll be the best tester, but I'll try!

**Comment by kobelobster** [comment]
PHPUnit output

```
PHPUnit 4.7.3 by Sebastian Bergmann and contributors.

..........

Time: 252 ms, Memory: 5.75Mb

OK (10 tests, 23 assertions)
```

Will now test it in normal use.

**Comment by cdarken** [comment]
I have forked the package, updated illuminate packages to 5.1.*, removed php version dependency, as the illuminate packages already need 5.5.9, installed in my project, ran the unit tests, works fine. If anybody else wants to test, put this into your composer.json:

```
"repositories": [
      {
        "type": "vcs",
        "url": "https://github.com/cdarken/laravel-jsonapi"
      }
    ]
```

 Then set version for the package to dev-master and run composer update. If all seems fine I will make a pull request.

**Comment by egeriis** [comment]
I myself am using the Laravel 4 version still, unfortunately. So I will not be able to test. Great work though, I will be ready to do a review of a pull request :)

**Comment by abhimanyu003** [comment]
@cdarken will be great if you create a pull request. I have tested your fork on very small app and it is  working fine.

**Comment by cdarken** [comment]
Done, pull request created.

**Comment by nurmanhabib** [comment]
+1

@tzfrs please merge pull request from @cdarken 

I have also experienced such problems. I am also waiting for an update JsonAPI relationship +1

**Comment by egeriis** [comment]
Pull request #19 merged

**Comment by SethArchambault** [comment]
I get this exact same error when requiring "echo-it/laravel-jsonapi" : "2.*"

What's the solution for this?

**Comment by egeriis** [comment]
@SethArchambault A tag for the latest revision was missing. It's been added now, so you should be able to require the library with Laravel 5.1 now.
