### ISSUE TITLE
How's this different from a resource controller?

### ISSUE THREAD

**Issue by malhal** [echo-it/laravel-jsonapi#20]
Thanks

**Comment by egeriis** [comment]
Hi @malhal 

It's different because the format of the response JSON adheres to the specified format at jsonapi.org.

It's also the aim of the library to support the features also described by JSONAPI, e.g. URI structure and specifying related documents to be included.

I hope this answers your question.

**Comment by malhal** [comment]
Hi the jsonapi.org spec is interesting. However I think you could have saved yourself some code by leveraging a few excellent Laravel features. A "Resource Controller" would handle the route params (model/id) and method type. Then instead of your try catch used a "Handler" subclass for the exception handling. For parsing the Request params would could have use a "Request" subclass. So like 3 classes needed, JSONAPISpecHandler, JSONAPISpecController, JSONAPISpecRequest (which validates the include/sort etc query params) and puts them into protected variables. It just crossed my mind a "Response" subclass for redering the response might be best so it can be used from the controller and in the exception handler. Doing it this way you let people code as normal, defining their routes, controllers etc without limiting them from the things they usually do hence you might get more users of the project. A basic example of this is by constraining all methods and models into one route, they can no longer turn off certain routes they don't want. Another example is they can't use model binding. So I believe rather than wrapping methods its much better to provide extra functionality in the form of subclasses dotted around the place, even better would be traits but they sometimes have too many limitations. The JSON spec looks really interesting, I wouldn't mind helping you with a new design if you like as I'm currently making a design that matches Apple's CloudKit JS spec and I'm sure a lot of the code will be the same. A similar project by the way is Fractal which I think could be used to easily make the response format.

Just a quick question about the JSONAPI spec, what does the 'vnd' in application/vnd.api+json stand for? can't see it in the faq. I hope its not embarassingly obvious ;-) 
http://jsonapi.org/examples/

**Comment by egeriis** [comment]
Hi again, 

After Laravel 5 came out I've wanted to explore the idea of using a Resource Controller and Middleware to work probably as you suggest. I cannot remember the incentive to utilize the current pattern with the initial implementation of this library, to be honest.

Fractal looks interesting. It seems like that has been an inspiration for Laravel's Collection implementation as well.

This project is always open to pull requests, and I'd be happy to collaborate in making it even better.

'vnd' doesn't stand for anything, actually. I was a bit confused when I first saw this MIME-type as well, thinking that you would replace 'vnd' with your vendor domain. You can read more about it here: https://en.wikipedia.org/wiki/Internet_media_type#Vendor_tree

**Comment by malhal** [comment]
It looks to me like JSON API doesn't have anything in the spec for batching creates/updates which is essential in any API to limit the number of network requests, furthermore you need a flag to be atomic so you can insert related data. Looks to me more like basic CRUD. In my experience designing for batch means redesigning the CRUD requests to be batchable and its usually easier to just start with batch design from the outset, like Apple's CloudKit JS spec has done.

Thanks for the offer to do a pull request, I've not tried that yet but will do soon.

Usually when its a placeholder its more obviously named, or at least as a comment saying so, that's why that didn't occur to me. Looks like you are right about the vendor tree, must be something widely known in the javascript community.
