### ISSUE TITLE
JSONAPI.org compliance

### ISSUE THREAD

**Issue by manuelfink** [echo-it/laravel-jsonapi#21]
Just being serious, is this lib compliant to jsonapi.org?
E.g I'm just wondering aren't attributes not supposed to be in an attributes child? http://jsonapi.org/format/#document-resource-object-attributes. For me the lib is returning attributes as a direkt child of each object and not underneath object.attributes.

**Comment by egeriis** [comment]
I believe we had a pull request not far ago, which updated this when the specification had been changed.

If it's not working as specified, you are very welcome to do a pull request.

**Comment by egeriis** [comment]
I just checked up and see that the PR wasn't merged due to conflicts. https://github.com/echo-it/laravel-jsonapi/pull/14

**Comment by egeriis** [comment]
#14 merged

**Comment by manuelfink** [comment]
Did you merge it?

2015-09-28 13:49 GMT+02:00 Ronni Egeriis Persson notifications@github.com:

**Comment by egeriis** [comment]
Yup, forgot to tag though. One minute.

**Comment by egeriis** [comment]
There we go. v2.4.
