### ISSUE TITLE
Use PATCH instead of PUT

### ISSUE THREAD

**Issue by mfn** [echo-it/laravel-jsonapi#23]
As per http://jsonapi.org/format/1.0/#crud-updating , `PATCH` is the actual verb to use, not `PUT`.

See also the FAQ: http://jsonapi.org/faq/#wheres-put

**Comment by egeriis** [comment]
Haven't seen that update. I am quite sure it's a simple fix to implement this. Feel free to open a PR!

**Comment by egeriis** [comment]
Ok if I close this? Or do you want to add something?

**Comment by mfn** [comment]
Yes, thanks, it's OK to close.

Please note however that I currently do not plan to implement `handlePatchDefault()`, thus the references PR is not a complete `PATCH` implementation, merely a start for whoever wants to complete it.

**Comment by egeriis** [comment]
Yup, that's perfect.
