### ISSUE TITLE
Use schema validation for generated responses

### ISSUE THREAD

**Issue by mfn** [echo-it/laravel-jsonapi#25]
May I suggest introducing schema validation by using the official [jsonapi schema](http://jsonapi.org/faq/#is-there-a-json-schema-describing-json-api) and a library like https://github.com/justinrainbow/json-schema ?

**Comment by egeriis** [comment]
Hi @mfn,
How do you imagine this to be integrated into this project?

**Comment by egeriis** [comment]
Closing this too for now.
