### ISSUE TITLE
HTTP response code when resource created

### ISSUE THREAD

**Issue by IAmJulianAcosta** [echo-it/laravel-jsonapi#4]
The [spec](http://jsonapi.org/format/#crud-creating-responses-201) says:

```
A server MUST respond to a successful resource creation request according to HTTP semantics.

When one or more resources has been created, the server MUST return a 201 Created status code.
```

But looking at this function: 

```
    public static function successfulHttpStatusCode($method)
    {
        switch ($method) {
            case 'PUT':
            case 'POST':
            case 'DELETE':
                return BaseResponse::HTTP_NO_CONTENT;

            case 'GET':
                return BaseResponse::HTTP_OK;
        }

        // Code shouldn't reach this point, but if it does we assume that the
        // client has made a bad request, e.g. PATCH
        return BaseResponse::HTTP_BAD_REQUEST;
    }
```

The response code for POST case is 204, instead of 201, is this wrong? Or I'm missing something?

**Comment by egeriis** [comment]
I think this is a bug, yes.

In my use case, I am overwriting the status code, because I always have timestamps and other fields on entities that are being updated by the server. And I return those in the response, thus it has to be a `200 OK` response, if I remember correctly.
