### ISSUE TITLE
Sorting can result in invalid links from paginator

### ISSUE THREAD

**Issue by mfn** [echo-it/laravel-jsonapi#41]
From `\EchoIt\JsonApi\Handler::handlePaginationRequest()`:

``` PHP
        if (!empty($request->sort)) {
            $paginator->appends('sort', implode(',', $request->sort));
        }
```

In case sorting is done via e.g. `+column` (needs to be encoded to `%2Bcolumn` in an actual request), `$paginator->appends` gets called with `+column` which will end up in the generate url with `sort= column` (note the space).

It seems encoding is applied again and thus needs to be escaped first.

Unfortunately `\Illuminate\Pagination\AbstractPaginator::addQuery()` is sparse on what the expectence is.

But in the end the query ends up in `\Illuminate\Pagination\AbstractPaginator::url()` which creates `$parameters`, containing the query and thus the sort, and runs it through `urldecode(http_build_query($parameters))`.

It seems the following fixes it, but I'm not sure about this approach:

``` DIFF
--- a/vendor/echo-it/laravel-jsonapi/src/EchoIt/JsonApi/Handler.php
+++ b/vendor/echo-it/laravel-jsonapi/src/EchoIt/JsonApi/Handler.php
@@ -468,7 +468,7 @@ abstract class Handler
             }
         }
         if (!empty($request->sort)) {
-            $paginator->appends('sort', implode(',', $request->sort));
+            $paginator->appends('sort', urlencode(implode(',', $request->sort)));
         }

         return $paginator;
```

Could be an oversight in the `Paginator` implementation?

**Comment by egeriis** [comment]
Seems like a hack to add `urlencode`. I didn't implement the pagination, so I'll have to take a brief look :)

**Comment by egeriis** [comment]
I think #44 will solve this?

**Comment by mfn** [comment]
I think so too; didn't test the code but it makes sense. No `+`, no problem :-)
